// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warningd67316f3ecc7776e233e61c2f6f3c7125938146a8a757bfe43ffc19a7965e00a() {}
