name: Cross-compilation test

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: build with cmake
      run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
